WebApp/Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using WebApp.Models.Options;
using System.IO.Compression;
using WebApp.Models.Service;

public class FileController : Controller
{
    private readonly IFileService _service;
    public FileController(IFileService service)
    {
        _service = service;
    }

    [HttpPost]
    public async Task<IActionResult> UploadFile(List<IFormFile> files, int userId, int page)
    {
        var message = await _service.UploadFile(files, userId);
        if (message != "successfully")
        {
            TempData["Message"] = message;
            TempData["isSuccess"] = false;
        }
        else
        {
            TempData["isSuccess"] = true;
            TempData["Message"] = "Files uploaded successfully";

        }
        return RedirectToAction("Details", "User", new { id = userId, currentPage = page });
    }

    [HttpGet]
    public IActionResult DownloadFile(string fileName, int userId)
    {
        var fileBytes = _service.DownloadFile(fileName, userId);

        var contentType = "application/octet-stream";

        return File(fileBytes, contentType, fileName);
    }

    [HttpPost]
    public IActionResult DownloadMultipleFiles(string[] selectedFiles, int userId)
    {
        if (selectedFiles.Count() > 0)
        {
            var memoryStream = _service.DownloadMultipleFiles(selectedFiles, userId);

            return File(memoryStream.ToArray(), "application/zip", "SelectedFiles.zip");
        }
        TempData["Message"] = "Select at least one file";
        TempData["isSuccess"] = false;
        return RedirectToAction("Details", "User", new { id = userId });

    }

    public async Task<IActionResult> DeleteFile(string fileName, int userId, int page)
    {
        var dl = new List<string>();
        dl.Add(fileName);
        var message = await _service.RemoveFiles(dl, userId);
        if (message != "successfully")
        {
            TempData["isSuccess"] = false;
            TempData["Message"] = message;
        }
        else
        {
            TempData["isSuccess"] = true;
            TempData["Message"] = $"{fileName} deleted successfuly";
        }
        return RedirectToAction("Details", "User", new { id = userId, currentPage = page });
    }

    public async Task<IActionResult> DeleteVideo(string fileName, int userId)
    {
        var dl = new List<string>();
        dl.Add(fileName);
        var message = await _service.RemoveFiles(dl, userId);
        if (message != "successfully")
        {
            return Ok(new { ok = false, mess = message});
        }
        else
        {
            return Ok(new { ok = true, mess = message});
        }
    }

    public async Task<IActionResult> DeleteMultipleFiles(string[] selectedFiles, int userId, int page)
    {
        if (selectedFiles.Count() == 0)
        {
            TempData["isSuccess"] = false;
            TempData["Message"] = "At least select one file";
        }
        else
        {
            await _service.RemoveFiles(selectedFiles, userId);
        }
        return RedirectToAction("Details", "User", new { id = userId, currentPage = page });
    }

}

WebApp/Controllers/TodoListController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Text.Json;

using WebApp.Models.Repositories;
using WebApp.Models.Service;
using WebApp.Models.TodoModel;

public class TodoListController : Controller
{
    private readonly ITodoService _service;
    public TodoListController(ITodoService service)
    {
        _service = service;
    }

    public IActionResult Index()
    {
        return View();
    }

    public async Task<IActionResult> AddTodo([FromForm] Todo t)
    {
        await _service.AddTodo(t);
        return Json(new { success = true, Todo = t });
    }

    public async Task<IActionResult> GetTodos(int userId)
    {
        var todos = await _service.GetTodos(userId);
        return Json(todos);
    }

    public async Task<IActionResult> DeleteTodo(int todoId)
    {
        await _service.DeleteTodo(todoId);
        return Json(new { success = true });
    }

    public async Task<IActionResult> Toggle(int todoId)
    {
        var todo = await _service.GetTodo(todoId);
        if (todo != null)
        {
            todo.done = (todo.done) ? false : true;
            await _service.UpdateTodo(todo);
            return Json(new { success = true });
        }
        return Json(new { success = false });
    }

    public IActionResult TodoListView()
    {
        return PartialView("_TodoList");
    }
}

WebApp/Controllers/TransactionController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models.TransactionModel;
using WebApp.Models.Service;
using WebApp.Models.Repositories;
using System.Threading.Tasks;
using Azure;

namespace WebApp.Controllers;

public class TransactionController : Controller
{
    private readonly ITransactionService _service;
    private readonly IUserService _userservice;
    public TransactionController(ITransactionService service, IUserService userservice)
    {
        _service = service;
        _userservice = userservice;
    }

    public async Task<IActionResult> Index()
    {
        var transactions = await _service.GetAllTransaction();
        var viewModels = new List<TransactionViewModel>();
        foreach (var trans in transactions)
        {

            var user = await _userservice.GetUser(trans.UserId);
            var transaction = new TransactionViewModel
            {
                Title = trans.Title,
                Amount = trans.Amount,
                Date = trans.Date,
                Category = trans.Category,
                IsIncome = trans.IsIncome,
                UserName = user.Username,
                Id = trans.Id
            };

            viewModels.Add(transaction);

        }
        return View(viewModels);
    }

    [HttpGet]
    public async Task<IActionResult> Create(int uid = 0, int page = 1)
    {
        if (uid != 0)
        {
            var user = await _userservice.GetUser(uid);
            ViewBag.UserName = user.Username;
        }
        else
        {
            ViewBag.UserName = null;
        }
        ViewBag.UserId = uid;
        var tran = new Transaction
        {
            Date = DateTime.Today
        };
        ViewBag.CurrentPage = page;
        return View(tran);
    }

    [HttpPost]
    public async Task<IActionResult> Create(Transaction transaction, string UserName, int userId = 0, int p = 1)
    {
        if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
        {
            if (ModelState.IsValid)
            {
                var title = await _service.AddTransaction(transaction, userId);

                return Json(new
                {
                    success = true,
                    message = $"{title} created successfully.",
                    userId = userId
                });
            }
            ViewBag.UserName = UserName;
            ViewBag.UserId = userId;
            ViewBag.CurrentPage = p;
            var model = new Transaction();
            return PartialView("_CreateTransaction", model);
        }
        else
        {
            var user = await _userservice.GetUserByUsername(UserName);
            if (user == null)
            {
                TempData["Error"] = $"User {UserName} not found.";
                return RedirectToAction("Create", new { uid = userId, page = p });
            }
            if (transaction.Title == null)
            {
                TempData["Error"] = "Please input Title";
                return RedirectToAction("Create", new { uid = userId, page = p });
            }
            if (transaction.Category == null)
            {
                TempData["Error"] = "Please select Category";
                return RedirectToAction("Create", new { uid = userId, page = p });
            }
            var title = await _service.AddTransaction(transaction, user.Id);
            TempData["Message"] = $"{title} created successfully.";

            return RedirectToAction("Details", "User", new { id = user.Id, currentPage = p });
        }

    }

    public async Task<IActionResult> Delete(int Id, int userId, int page)
    {
        await _service.DeleteTransaction(Id);

        if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
        {
            return Json(new { success = true });
        }

        TempData["Message"] = "Transaction deleted successfully.";
        return RedirectToAction("Details", "User", new { id = userId, currentPage = page });

    }

    [HttpGet]
    public async Task<IActionResult> CreatePartial(int uid, int? page)
    {
        if (uid != 0)
        {
            var user = await _userservice.GetUser(uid);
            ViewBag.UserName = user.Username;
        }
        else
        {
            ViewBag.UserName = null;
        }
        ViewBag.UserId = uid;
        ViewBag.CurrentPage = page;
        var model = new Transaction();
        return PartialView("_CreateTransaction", model);
    }

    [HttpGet]
    public async Task<IActionResult> TransactionTablePartial(int userId, int page = 1)
    {
        var user = await _userservice.GetUser(userId);
        if (user == null)
        {
            return NotFound();
        }

        var transactions = await _service.GetUserAllTransactions(userId);
        var viewModels = transactions.Select(trans => new TransactionViewModel
        {
            Title = trans.Title,
            Amount = trans.Amount,
            Date = trans.Date,
            Category = trans.Category,
            IsIncome = trans.IsIncome,
            UserName = user.Username,
            Id = trans.Id
        }).ToList();

        ViewBag.UserId = userId;
        ViewBag.currentPage = page;
        ViewBag.ShowExportButton = true;
        return PartialView("_TransactionsTable", viewModels);
    }
}

WebApp/Controllers/VideoController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Models.Service;
using WebApp.Models.PlayBackLogModel;
using WebApp.Models.UploadedFileModel;
using WebApp.Models.Repositories;

namespace WebApp.Controllers;

/// <summary>
/// 影片控制器
/// 處理影片的播放、上傳、分片等功能
/// </summary>
public class VideoController : Controller
{
    private readonly IVideoService _service;

    private readonly IFileService _file_service;

    private readonly WebSocketService _socket_service;
    /// <summary>
    /// 建構函數
    /// </summary>
    /// <param name="service">影片服務</param>
    /// <param name="file_service">檔案服務</param>
    /// <param name="socket_service">WebSocket服務</param>
    public VideoController(IVideoService service, IFileService file_service, WebSocketService socket_service)
    {
        _service = service;
        _file_service = file_service;
        _socket_service = socket_service;

    }
    /// <summary>
    /// 顯示 Youtube IFrame 影片頁面
    /// </summary>
    public IActionResult Index()
    {
        return View();
    }
    /// <summary>
    /// 播放指定影片
    /// </summary>
    /// <param name="id">影片ID</param>
    /// <returns>影片播放頁面</returns>
    public async Task<IActionResult> Play(int id)
    {
        var video = await _file_service.Get(id);
        var path = video.FilePath;
        video.FilePath = path.Substring(path.IndexOf("wwwroot") + 7);
        ViewBag.Type = Path.GetExtension(video.FileName).Substring(1);
        return View(video);
    }

    /// <summary>
    /// 處理影片分片上傳
    /// </summary>
    /// <param name="chunk">影片分片檔案</param>
    /// <param name="fileId">檔案唯一識別碼</param>
    /// <param name="chunkIndex">分片索引</param>
    /// <returns>上傳結果</returns>
    [HttpPost]
    public async Task<IActionResult> Chunk(IFormFile chunk, string fileId, int chunkIndex)
    {
        if (chunk == null || string.IsNullOrEmpty(fileId))
            return BadRequest("Missing parameters");

        var path = await _service.UploadChunk(chunk, fileId, chunkIndex);

        return Ok(new { ok = true, savedAs = path });
    }

    /// <summary>
    /// 合併已上傳的影片分支
    /// </summary>
    /// <param name="fileId">檔案唯一識別碼</param>
    /// <param name="filename">檔案名稱</param>
    /// <param name="totalChunks">總分片數</param>
    /// <param name="userId">使用者ID</param>
    /// <returns>合併結果</returns>
    [HttpPost]
    public async Task<IActionResult> Merge(string fileId, string filename, int totalChunks, int userId)
    {
        var path = await _service.Merge(fileId, filename, totalChunks, userId);
        if (!System.IO.File.Exists(path))
        {
            return StatusCode(500, path);
        }
        path = path.Substring(path.IndexOf("wwwroot") + 7);
        return Ok(new { ok = true, output = path });
    }

    /// <summary>
    /// 檢查影片是否存在
    /// </summary>
    /// <param name="videoId">影片ID</param>
    /// <param name="userId">用戶ID</param>
    /// <returns>檢查結果</returns>
    public async Task<IActionResult> CheckVideo(string videoId, int userId)
    {
        return Json(new { success = await _service.CheckVideo(videoId, userId) });
    }

    /// <summary>
    /// 紀錄影片播放位置
    /// </summary>
    /// <param name="userId">用戶ID</param>
    /// <param name="videoId">影片ID</param>
    /// <param name="lp">最後播放位置(秒)</param>
    /// <returns>紀錄結果</returns>
    [HttpPost]
    public async Task<IActionResult> Record(int userId, string videoId, int lp)
    {
        var log = new PlayBackLog
        {
            UserId = userId,
            VideoId = videoId,
            LastPosition = lp,
            UpdateAt = DateTime.Now
        };

        await _service.Record(log);

        return Ok(new { ok = true });
    }
    
    /// <summary>
    /// 獲取影片播放紀錄
    /// </summary>
    /// <param name="userId">用戶ID</param>
    /// <param name="videoId">影片ID</param>
    /// <returns></returns>
    [HttpGet]
    public async Task<IActionResult> GetLog(int userId, string videoId)
    {
        var log = await _service.GetLog(userId, videoId);
        return Ok(new
        {
            lastPosition = log?.LastPosition ?? 0
        });
    }
}

WebApp/Views/Shared/_AlertMessage.cshtml
@model dynamic

@if (Model.Message != null)
{
    <div class="alert @Model.AlertClass alert-dismissible fade show" role="alert">
        @Model.Message
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

WebApp/Views/Shared/_CreateTransaction.cshtml
@model WebApp.Models.TransactionModel.Transaction
@using WebApp.Models.TransactionModel
@{
    var userName = ViewBag.UserName;
    var userId = ViewBag.UserId;
    var currentPage = ViewBag.CurrentPage;
}
<form asp-controller="Transaction" asp-action="Create">
    <div class="mb-3">
        <label for="UserName" class="form-label">User Name</label>
        @if(userName != null){
            <input type="text" value="@userName" name="UserName" id="UserName" class="form-control" readonly />
            <input type="hidden" value="@userId" name="userId" id="userId" />
            <input type="hidden" value="@currentPage" name="p" id="p" />
        }else{
            <input type="text" name="UserName" id="UserName" class="form-control" />
        }
    </div>

    <div class="mb-3">
        <label asp-for="Title" class="form-label">Title</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Amount" class="form-label">Amount</label>
        <input asp-for="Amount" class="form-control" type="number" step="0.01" min="0" />
        <span asp-validation-for="Amount" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Date" class="form-label">Date</label>
        <input asp-for="Date" class="form-control" type="date" value="@DateTime.Today.ToString("yyyy-MM-dd")"
               min="@DateTime.Today.AddYears(-1).ToString("yyyy-MM-dd")"
               max="@DateTime.Today.ToString("yyyy-MM-dd")" />
        <span asp-validation-for="Date" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Category" class="form-label">Category</label>
        <select asp-for="Category" class="form-select">
            <option value="0" selected>Select a category</option>
            @foreach (var category in Enum.GetValues(typeof(Category)))
            {
                if ((Category)category == Category.None) continue; // 跳過 None
                <option value="@category">@category.ToString()</option>
            }
        </select>
        <span asp-validation-for="Category" class="text-danger"></span>
    </div>

    <div class="d-flex justify-content-end">
        <button type="submit" class="btn btn-primary me-2">Create</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    </div>
</form>

WebApp/Views/Shared/_CreateTransactionModal.cshtml
<div class="modal fade" id="createTransactionModal" tabindex="-1" aria-labelledby="createTransactionModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createTransactionModalLabel">Create New Transaction</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

WebApp/Views/Shared/_CreateUser.cshtml
@model WebApp.Models.UserModel.User

<form id="createUserForm">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group mb-3">
        <label asp-for="Username" class="control-label"></label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>

    <div class="form-group mb-3">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Create</button>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
    </div>
</form>

WebApp/Views/Shared/_DetailActionButtons.cshtml
@model dynamic

<div class="mb-3 d-flex justify-content-between align-items-center">
    <div>
        <a asp-action="Edit" asp-route-id="@Model.UserId" class="btn btn-warning">
            <i class="bi bi-pencil"></i> Edit User
        </a>
        <a asp-controller="@Model.ComeFrom" asp-action="Index" asp-route-page="@Model.CurrentPage" 
           class="btn btn-secondary">
            <i class="bi bi-arrow-left"></i> Back to List
        </a>
    </div>
    
    <partial name="_ExportButtons" model="@Model.UserId" />
</div>

WebApp/Views/Shared/_ExportButton.cshtml
@model dynamic
<div class="mb-3 d-flex justify-content-between align-items-center">
    <div>
        <!-- 改為按鈕並設定要載入的 URL -->
        <button type="button" class="btn btn-primary open-create-modal"
                data-url="@Url.Action("CreatePartial", "Transaction", new { uid = @Model.uid, page = @Model.page })">
            <i class="bi bi-plus-circle"></i> Add
        </button>
    </div>

    <div class="btn-group">
        <button type="button" class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            Export
        </button>
        <ul class="dropdown-menu">
            <li>
                <button type="submit" class="dropdown-item" formaction="@Url.Action("ExportTransactionToExcel", "ImportExport")">Excel</button>
            </li>
            <li>
                <button type="submit" class="dropdown-item" formaction="@Url.Action("ExportTransactionPDF", "ImportExport")">PDF</button>
            </li>
        </ul>
    </div>
</div>

WebApp/Views/Shared/_ExportButtons.cshtml
@model int
<div class="btn-group">
    <a asp-controller="ImportExport" asp-action="SendUserReport" asp-route-id="@Model" 
       class="btn btn-success">
        <i class="bi bi-mailbox"></i> Send Report
    </a>
    <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">
        Export Report
    </button>
    <ul class="dropdown-menu">
        <li><a class="dropdown-item" asp-controller="ImportExport" asp-action="UserReport" 
               asp-route-id="@Model">Default</a></li>
        <li><a class="dropdown-item" asp-controller="ImportExport" asp-action="UserReportFromTemplate" 
               asp-route-id="@Model">From Template</a></li>
        <li><a class="dropdown-item" asp-controller="ImportExport" asp-action="UserReportPdf" 
               asp-route-id="@Model">Default - PDF</a></li>
        <li><a class="dropdown-item" asp-controller="ImportExport" asp-action="UserReportFromTemplatPdf" 
               asp-route-id="@Model">From Template - PDF</a></li>
        <li><a class="dropdown-item" asp-controller="ImportExport" asp-action="UserReportPdf" 
               asp-route-id="@Model" asp-route-watermark="@true">Default - PDF (Paid)</a></li>
        <li><a class="dropdown-item" asp-controller="ImportExport" asp-action="UserReportFromTemplatPdf" 
               asp-route-id="@Model" asp-route-watermark="@true">From Template - PDF (Paid)</a></li>
    </ul>
</div>

WebApp/Views/Shared/_FileList.cshtml
@using WebApp.Models.UploadedFileModel
@model WebApp.Models.UserModel.User

@{
    var files = ViewBag.Files as List<UploadedFile>;
    var currentPage = Convert.ToInt32(ViewData["CurrentPage"] ?? 1);
}

@functions {
    string FormatFileSize(long bytes)
    {
        string[] sizes = { "B", "KB", "MB", "GB", "TB" };
        double len = bytes;
        int order = 0;

        while (len >= 1024 && order < sizes.Length - 1)
        {
            order++;
            len /= 1024;
        }

        return $"{len:F2} {sizes[order]}";
    }
}

@if (files != null && files.Count > 0)
{
    <form asp-controller="File" asp-action="DownloadMultipleFiles" asp-route-userId="@Model.Id" method="post">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>Select</th>
                    <th>File Name</th>
                    <th>File Size</th>
                    <th>Download</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var file in files)
                {
                    <tr class="text-center">
                        <td><input type="checkbox" name="selectedFiles" value="@file.FileName" /></td>
                        <td>
                            <a href = "@file.FilePath.Substring(7)">@file.FileName</a>
                        </td>
                        <td>@FormatFileSize(file.FileSize)</td>
                        <td class="align-middle"><a href="/File/DownloadFile?fileName=@file.FileName&userId=@Model.Id&page=@currentPage"><i class="bi bi-download"></i></a></td>
                        <td class="align-middle">
                            <a asp-controller="File" asp-action="DeleteFile" asp-route-fileName=@file.FileName asp-route-userId=@Model.Id asp-route-page=@currentPage method="post" style="display: inline; color: red;" onclick="return confirm('Are you sure you want to delete this file?');">
                                <i class="bi bi-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
            <button type="submit" class="btn btn-primary bi bi-download">Download selected files</button>
            <button type="submit" class="btn btn-danger" formaction="@Url.Action("DeleteMultipleFiles", "File", new { userId = @Model.Id, page = @currentPage })" onclick="return confirm('Are you sure you want to delete these file?');"><i class="bi bi-trash"></i>Deleted selected files</button>
    </form>
}else
{
    <div class="alert alert-info">No files found for this user.</div>
}

WebApp/Views/Shared/_Pagination.cshtml
@{
    var currentPage = Convert.ToInt32(ViewData["CurrentPage"] ?? 1);
    var totalPages = ViewBag.TotalPages ?? 1;
}

@if (totalPages > 1)
{
    <nav aria-label="Page navigation">
        <ul id = "Pagination" class="pagination justify-content-center">
            <li class="page-item @(currentPage == 1 ? "disabled" : "")">
                <a class="page-link" data-page= @(currentPage - 1) href="@Url.Action("Index", new { page = currentPage - 1 })">&laquo; Previous</a>
            </li>
            
            @for (int i = 1; i <= totalPages; i++)
            {
                <li class="page-item @(i == currentPage ? "active" : "")">
                    <a class="page-link" data-page= @i href="@Url.Action("Index", new { page = i })">@i</a>
                </li>
            }

            <li class="page-item @(currentPage == totalPages ? "disabled" : "")">
                <a class="page-link" data-page= @(currentPage + 1) href="@Url.Action("Index", new { page = currentPage + 1 })">Next &raquo;</a>
            </li>
        </ul>
    </nav>
}

<script>
    window.totalPages = @totalPages;
</script>

WebApp/Views/Shared/_TodoList.cshtml
<head>
  <meta charset="UTF-8">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="~/js/todoList.js"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
  <style>
    #todoBody {
      font-family: 'Arial', sans-serif;
      display: flex;
      justify-content: center;
      padding: 20px;
    }

    #todo {
      background-color: #fff;
      padding: 30px 40px;
      border-radius: 10px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
      width: 600px;
    }

    h2 {
      text-align: center;
      margin-bottom: 20px;
      color: #333;
    }

    #todoForm {
      display: flex;
      gap: 10px;
      margin-bottom: 15px;
    }

    #todoInput {
      flex: 1;
      padding: 8px 10px;
      border-radius: 5px;
      border: 1px solid #ccc;
      font-size: 14px;
    }

    #todoForm button {
      padding: 8px 12px;
      background-color: #007bff;
      color: #fff;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      font-size: 14px;
      transition: background-color 0.3s;
    }

    #todoForm button:hover {
      background-color: #0056b3;
    }

    .error {
      display: block;
      margin-top: 5px;
      color: red;
      font-size: 0.85em;
    }

    #todoList {
      list-style: none;
      padding: 0;
    }

    #todoList li {
      display: flex;
      justify-content: space-between;
      align-items: center;
      background-color: #f9f9f9;
      padding: 10px 15px;
      border-radius: 5px;
      margin-bottom: 8px;
      cursor: pointer;
      transition: background-color 0.2s;
    }

    #todoList li:hover {
      background-color: #e9ecef;
    }

    #todoList li.done {
      text-decoration: line-through;
      color: #6c757d;
      background-color: #e9ecef;
    }

    #todoList li.done:hover {
      background-color: #f9f9f9;
    }
  </style>
</head>
<div id="todoBody">
    <div id="todo">
        <h2>To-do List</h2>

        <!-- 表單 -->
        <form id="todoForm">
            <input type="text" id="todoInput" placeholder="Enter To-Do Items">
            <button type="submit">Add</button>
        </form>
        <span class="error" id="errorMsg"></span>

        <!-- 清單 -->
        <ul id="todoList"></ul>
    </div>
    <div id="loadingSpinner" style="display:none; position:fixed; top:50%; left:50%; transform:translate(-50%,-50%);">
      <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Loading...</span>
      </div>
  </div>
</div>

WebApp/Views/Shared/_VideoList.cshtml
@using WebApp.Models.UploadedFileModel
@model WebApp.Models.UserModel.User

@{
    var videos = ViewBag.Videos as List<UploadedFile>;
    var currentPage = Convert.ToInt32(ViewData["CurrentPage"] ?? 1);
}


@if (videos != null && videos.Count > 0)
{
    <form asp-controller="File" asp-action="DeleteMultipleFiles" asp-route-userId="@Model.Id" asp-route-page="@currentPage" method="post">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th>Select</th>
                    <th>Video Name</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var video in videos)
                {
                    <tr class="text-center">
                        <td><input type="checkbox" name="selectedFiles" value="@video.FileName" /></td>
                        <td>
                            <a asp-controller="Video" asp-action="Play" asp-route-id="@video.Id">@video.FileName</a>
                        </td>
                        <td class="align-middle">
                            @* <a asp-controller="File" asp-action="DeleteFile" asp-route-fileName=@video.FileName asp-route-userId=@Model.Id asp-route-page=@currentPage method="post" style="display: inline; color: red;" onclick="return confirm('Are you sure you want to delete this file?');">
                                <i class="bi bi-trash"></i>
                            </a> *@
                            <a href="#" style="display: inline; color: red;">
                                <i id="deleteBtn" data-userid="@Model.Id" data-filename="@video.FileName" class="bi bi-trash"></i>
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
            <button type="submit" class="btn btn-danger bi bi-trash">Deleted selected files</button>
    </form>
}else
{
    <div class="alert alert-info">No video found for this user.</div>
}

WebApp/Views/Shared/_VideoUploadForm.cshtml
<div class="mb-3">
    <div class="input-group">
        <input type="file" id="videoInput" class="form-control" accept="video/*"/>
        <button id="uploadBtn" class="btn btn-primary">
            <i class="bi bi-upload"></i> Upload Video
        </button>
    </div>
    <progress id="progressBar" value="0" max="100" class="w-100 mt-2"></progress>
    <p id="status" class="text-muted"></p>
</div>