WebApp/Controllers/ImportExportController.cs
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using System.IO;
using System.Threading.Tasks;
using System.Linq;
using WebApp.Models.Service;
using System.Reflection;
using WebApp.Models.UserModel;
using WebApp.Models.TransactionModel;
using iTextSharp.text;
using iTextSharp.text.pdf;



public class ImportExportController : Controller
{
    private readonly IUserService _userservice;
    private readonly ITransactionService _transactionservice;

    private readonly IImportExportService _service;

    public ImportExportController(IUserService userservice, ITransactionService transactionservice, IImportExportService service)
    {
        _userservice = userservice;
        _transactionservice = transactionservice;
        _service = service;
    }


    [HttpGet]
    public IActionResult Import(string comeFrom)
    {
        ViewBag.comeFrom = comeFrom;
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> ImportUserFile(IFormFile file)
    {
        if (file == null || file.Length == 0 || !Path.GetExtension(file.FileName).ToLowerInvariant().Equals(".xlsx"))
        {
            TempData["Warning"] = "Please select a valid Excel file.";
            return RedirectToAction("Import", new { comeFrom = "User" });
        }

        var importedData = await _service.ImportUserFile(file);
        return View(importedData);

    }

    public async Task<IActionResult> ImportTransactionFile(IFormFile file)
    {
        if (file == null || file.Length == 0 || !Path.GetExtension(file.FileName).ToLowerInvariant().Equals(".xlsx"))
        {
            TempData["Warning"] = "Please select a valid Excel file.";
            return RedirectToAction("Import", new { comeFrom = "Transaction" });
        }

        var importedData = await _service.ImportTransactionFile(file);
        return View(importedData);
    }

    public async Task<IActionResult> ConvertExcelToPdf(IFormFile file, string cf, string package)
    {
        if (file == null || file.Length == 0 || !Path.GetExtension(file.FileName).ToLowerInvariant().Equals(".xlsx"))
        {
            TempData["Warning"] = "Please select a valid Excel file.";
            return RedirectToAction("Import", new { comeFrom = cf });
        }
        var pdfStream = await _service.ConvertExcelToPdf(file, package);

        string pdfName = $"{Path.GetFileNameWithoutExtension(file.FileName)}_{package}.pdf";

        return File(pdfStream.ToArray(), "application/pdf", pdfName);
    }

    public async Task<IActionResult> ExportAllUserToExcel()
    {
        var users = await _userservice.GetUserOverview();
        users = users.OrderBy(u => u.UserName);

        var stream = _service.ExportUserToExcel(users);

        string excelName = $"User_{System.DateTime.Now:yyyyMMddHHmmss}.xlsx";

        return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);

    }

    public async Task<IActionResult> ExportAllTransactionToExcel()
    {
        var transactions = await _transactionservice.GetAllTransaction();
        transactions = transactions.OrderBy(t => t.UserId);

        var stream = await _service.ExportTransactionToExcel(transactions);

        string excelName = $"Transaction_{System.DateTime.Now:yyyyMMddHHmmss}.xlsx";

        return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);

    }

    public async Task<IActionResult> ExportTransactionToExcel(IEnumerable<TransactionViewModel> transactions)
    {
        var tran = new List<Transaction>();
        foreach (var trans in transactions)
        {
            var user = await _userservice.GetUserByUsername(trans.UserName);

            var transaction = new Transaction
            {
                Title = trans.Title,
                Amount = trans.Amount,
                Date = trans.Date,
                Category = trans.Category,
                UserId = user.Id
            };

            tran.Add(transaction);
        }
        var stream = await _service.ExportTransactionToExcel(tran);

        string excelName = $"Transaction_{System.DateTime.Now:yyyyMMddHHmmss}.xlsx";

        return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
    }
    public async Task<IActionResult> ExportToExcel(string item)
    {
        // ExcelPackage.License.SetNonCommercialPersonal("Stanlin");

        var data = null as IEnumerable<object>;
        var properties = null as PropertyInfo[];

        if (item.ToLower() == "users")
        {
            var user = await _userservice.GetAllUsers();
            data = user.OrderBy(u => u.Username);
            properties = typeof(User).GetProperties(BindingFlags.Public | BindingFlags.Instance);

        }
        else if (item.ToLower() == "transactions")
        {
            data = await _transactionservice.GetAllTransaction();
            properties = typeof(Transaction).GetProperties(BindingFlags.Public | BindingFlags.Instance);

        }
        else
        {
            return BadRequest("Invalid item type. Please specify 'users' or 'transactions'.");
        }

        using (var package = new ExcelPackage())
        {
            var worksheet = package.Workbook.Worksheets.Add(item);

            // 填入標題列
            for (int i = 0; i < properties.Length; i++)
            {
                worksheet.Cells[1, i + 1].Value = properties[i].Name;
            }

            // 填入資料列
            for (int row = 0; row < data.Count(); row++)
            {
                for (int col = 0; col < properties.Length; col++)
                {
                    var value = properties[col].GetValue(data.ElementAt(row));
                    worksheet.Cells[row + 2, col + 1].Value = value;
                }
            }

            // 自動調整欄寬
            worksheet.Cells.AutoFitColumns();

            var stream = new MemoryStream();
            package.SaveAs(stream);
            stream.Position = 0;

            string excelName = $"Export_{System.DateTime.Now:yyyyMMddHHmmss}.xlsx";

            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
        }
    }


    public async Task<IActionResult> ExportAllUserToPDF()
    {
        var users = await _userservice.GetUserOverview();
        users = users.OrderBy(u => u.UserName);
        var pdfStream = _service.ExportUserToPDF(users);
        string pdfName = $"User_{System.DateTime.Now:yyyyMMddHHmmss}.pdf";

        return File(pdfStream.ToArray(), "application/pdf", pdfName);
    }

    // public IActionResult ExportUserPDF(IEnumerable<User> users)
    // {
    //     var pdfStream = _service.ExportUserToPDF(users);
    //     string pdfName = $"User_{System.DateTime.Now:yyyyMMddHHmmss}.pdf";
    //     return File(pdfStream.ToArray(), "application/pdf", pdfName);
    // }

    public async Task<IActionResult> ExportAllTransactionToPDF()
    {
        var transactions = await _transactionservice.GetAllTransaction();
        var users = await _userservice.GetAllUsers();

        var transactionViewModels = transactions
            .OrderBy(t => t.UserId)
            .Select(t => new TransactionViewModel
            {
                Title = t.Title,
                Amount = t.Amount,
                Date = t.Date,
                Category = t.Category,
                IsIncome = t.IsIncome,
                UserName = users.FirstOrDefault(u => u.Id == t.UserId)?.Username ?? "Unknown",
                Id = t.Id
            })
            .ToList();

        var pdfStream = await _service.ExportTransactionToPDF(transactionViewModels);
        string pdfName = $"Transaction_{DateTime.Now:yyyyMMddHHmmss}.pdf";
        return File(pdfStream.ToArray(), "application/pdf", pdfName);
    }

    public async Task<IActionResult> ExportTransactionPDF(IEnumerable<TransactionViewModel> transactions)
    {
        var pdfStream = await _service.ExportTransactionToPDF(transactions);
        string pdfName = $"Transaction_{System.DateTime.Now:yyyyMMddHHmmss}.pdf";
        return File(pdfStream.ToArray(), "application/pdf", pdfName);
    }


    public async Task<IActionResult> Save_User(IEnumerable<User> users)
    {
        var mes = await _userservice.AddUsers(users);
        if (mes.ContainsKey("Warning"))
            TempData["Warning"] = mes["Warning"];

        if (mes.ContainsKey("Message"))
            TempData["Message"] = mes["Message"];
            
        return RedirectToAction("Index", "User");
    }

    [HttpPost]
    public async Task<IActionResult> Save_Transaction(IEnumerable<TransactionViewModel> transactions)
    {
        var mes = await _transactionservice.AddTransactions(transactions);

        if (mes.ContainsKey("Warning"))
            TempData["Warning"] = mes["Warning"];

        if (mes.ContainsKey("Message"))
            TempData["Message"] = mes["Message"];

        return RedirectToAction("Index", "Transaction");
    }

    public IActionResult Discard_User()
    {
        TempData["Message"] = "Import operation discarded.";
        return RedirectToAction("Index", "User");
    }

    public IActionResult Discard_Transaction()
    {
        TempData["Message"] = "Import operation discarded.";
        return RedirectToAction("Index", "Transaction");
    }

    [HttpGet]
    public async Task<IActionResult> UserReport(int id)
    {
        var user = await _userservice.GetUser(id);
        if (user == null) return NotFound();

        var transactions = await _transactionservice.GetUserAllTransactions(id);
        transactions = transactions.OrderByDescending(t => t.Date);

        var ms = await _service.GenerateUserReportAsync(user, transactions.ToList());
        var fileName = $"UserReport_{user.Username}_{DateTime.Now:yyyyMMddHHmmss}.docx";

        return File(ms.ToArray(),
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            fileName);
    }

WebApp/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using WebApp.Models.UserModel;
using WebApp.Models.TransactionModel;
using WebApp.Models.Service;
using System.Transactions;


namespace WebApp.Controllers;

public class UserController : Controller
{
    private readonly IUserService _service;
    private readonly ITransactionService _transaction_service;

    private readonly IBudgetService _budget_service;

    private readonly IFileService _file_service;

    private readonly IMailService _mail_service;

    private readonly IVideoService _video_service;

    int PageSize = 10;


    public UserController(IUserService service, ITransactionService transaction_service, IBudgetService budget_service, IFileService file_service, IMailService mail_service, IVideoService video_service)
    {
        _service = service;
        _transaction_service = transaction_service;
        _budget_service = budget_service;
        _file_service = file_service;
        _mail_service = mail_service;
        _video_service = video_service;
    }

    public async Task<IActionResult> Index(int page = 1)
    {
        var users = await _service.GetUserOverview();

        var totalUsers = users.Count();
        var totalPages = (int)Math.Ceiling(totalUsers / (double)PageSize);

        users = users.OrderBy(u => u.UserName);
        users = users.Skip((page - 1) * PageSize).Take(PageSize).ToList();

        // ViewBag.Users = users;
        ViewData["CurrentPage"] = page;
        ViewBag.TotalPages = totalPages;

        return View(users);
    }


    [HttpGet]
    public IActionResult Create()
    {
        return View(new User());
    }

    [HttpPost]
    public async Task<IActionResult> Create(User user)
    {
        var mes = await _service.AddUser(user);
        if (mes["isSuccess"].Equals("false"))
        {
            TempData["isSuccess"] = false;
            TempData["Message"] = mes["Message"];
            return View();
        }
        TempData["isSuccess"] = true;
        TempData["Message"] = mes["Message"];
        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> UserTablePartial(int page = 1)
    {
        var users = await _service.GetUserOverview();

        var totalUsers = users.Count();
        var totalPages = (int)Math.Ceiling(totalUsers / (double)PageSize);

        users = users.OrderBy(u => u.UserName);
        users = users.Skip((page - 1) * PageSize).Take(PageSize).ToList();

        ViewData["CurrentPage"] = page;
        ViewBag.TotalPages = totalPages;
        return PartialView("_UsersTable", users);
    }

    public IActionResult CreatePartial()
    {
        return PartialView("_CreateUser");
    }

    public async Task<IActionResult> CreateAjax(User user)
    {
        if (ModelState.IsValid)
        {
            var mes = await _service.AddUser(user);

            if (mes["isSuccess"].Equals("false"))
            {
                return Json(new { success = false, message = mes["Message"] });
            }
            return Json(new { success = true, message = mes["Message"] });

        }

        return PartialView("_CreateUser", user);
    }

    public IActionResult Pagination(int page, int totalPages)
    {
        ViewData["CurrentPage"] = page;
        ViewBag.TotalPages = totalPages;
        return PartialView("_Pagination");
    }
    public async Task<IActionResult> Delete(int id, int currentPage = 1)
    {
        var name = await _service.DeleteUser(id);

        await _file_service.RemoveUserFold(id);
        await _video_service.DeleteUserVideo(id);


        TempData["Message"] = $"{name} deleted successfully.";
        ViewData["CurrentPage"] = currentPage;

        return RedirectToAction("Index", new { page = currentPage });
    }

    public async Task<IActionResult> DeleteAlluser()
    {
        var users = await _service.GetAllUsers();

        await _service.DeleteUsers(users);

        await _file_service.RemoveAllFile();

        return RedirectToAction("Index");
    }

    [HttpGet]
    public async Task<IActionResult> Edit(int id)
    {
        var user = await _service.GetUser(id);
        if (user == null)
        {
            return NotFound();
        }
        return View(user);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(User user)
    {
        var mes = await _service.UpdateUser(user);
        if (mes["isSuccess"].Equals("false"))
        {
            TempData["isSuccess"] = false;
            TempData["Message"] = mes["Message"];
        }
        else
        {
            TempData["isSuccess"] = true;
            TempData["Message"] = mes["Message"];
        }
        return RedirectToAction("Details", new { user.Id });
    }

    [HttpGet]
    public async Task<IActionResult> Details(int id = 0, int currentPage = 1, string userName = "", string comeFrom = "User")
    {
        var user = new User();
        if (userName != "" && id == 0)
        {
            user = await _service.GetUserByUsername(userName);
        }
        else
        {
            user = await _service.GetUser(id);
        }

        var budgets = await _budget_service.GetUserBudgets(user.Id);

        if (!budgets.Any())
        {
            await _budget_service.InitUserBudget(user.Id);
            budgets = await _budget_service.GetUserBudgets(user.Id);
        }

        var transactions = await _transaction_service.GetUserAllTransactions(user.Id);
        var viewModels = new List<TransactionViewModel>();
        foreach (var trans in transactions)
        {
            var transaction = new TransactionViewModel
            {
                Title = trans.Title,
                Amount = trans.Amount,
                Date = trans.Date,
                Category = trans.Category,
                IsIncome = trans.IsIncome,
                UserName = user.Username,
                Id = trans.Id
            };

            viewModels.Add(transaction);

        }

        var files = await _file_service.GetUserFiles(user.Id);
        var videos = await _video_service.GetUserVideos(user.Id);

        var categoryDistribution = await _transaction_service.GetCategoryDistribution(user.Id);

        ViewBag.ComeFrom = comeFrom;
        ViewBag.Files = files;
        ViewBag.Videos = videos;
        ViewBag.Budgets = budgets;
        ViewBag.CategoryDistribution = categoryDistribution;

        ViewBag.Transactions = viewModels;
        ViewData["CurrentPage"] = currentPage;

        return View(user);
    }

    [HttpGet]
    public async Task<IActionResult> EditBudget(int id, int currentPage = 1)
    {
        var budget = await _budget_service.GetUserBudgets(id);

        ViewBag.userId = id;
        ViewBag.currentPage = currentPage;

        return View(budget);
    }

    [HttpPost]
    public async Task<IActionResult> EditBudget(Dictionary<string, decimal?> limits, int id, int currentPage = 1)
    {
        var budgets = await _budget_service.GetUserBudgets(id);
        foreach (var limit in limits)
        {
            var budget = budgets.Where(b => b.Category.Equals(limit.Key)).FirstOrDefault();
            if (budget != null)
            {
                budget.setLimit(limit.Value);
                await _budget_service.UpdateBudget(budget);   
            }
        }

        return RedirectToAction("Details", new { id, currentPage });
    }

    public async Task<IActionResult> VideoList(int userId)
    {   
        var videos = await _video_service.GetUserVideos(userId);
        ViewBag.Videos = videos;
        var user = await _service.GetUser(userId);
        return PartialView("_VideoList", user);
    }
}

WebApp/Views/User/Create.cshtml
@model WebApp.Models.UserModel.User
@{
    ViewBag.Title = "Create New User";

    var message = TempData["Message"];
    var isSuccess = TempData["isSuccess"] !=null && (bool) TempData["isSuccess"];
    string alertClass = isSuccess ? "alert-success" : "alert-warning";
}

@if (message != null)
{
    <div class="alert @alertClass alert-dismissible fade show" role="alert">
        @message
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1>@ViewBag.Title</h1>

            <div class="row" >
                <div class="col-md-6">
                    <form asp-controller="User" asp-action="Create" method="post">
                        <div class="form-group mb-3">
                            <label asp-for="Username" class="control-label">Username</label>
                            <input asp-for="Username" class="form-control" />
                        </div>
            
                        <div class="form-group mb-3">
                            <label asp-for="Email" class="control-label">Email</label>
                            <input asp-for="Email" class="form-control" />
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Create</button>
                            <a asp-controller="User" asp-action="Index" class="btn btn-secondary">Back to List</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebApp/Views/User/Details.cshtml
@model WebApp.Models.UserModel.User
@{
    ViewBag.Title = "User Details";
    
    // Initialize view data
    var transactions = ViewBag.Transactions as List<WebApp.Models.TransactionModel.TransactionViewModel>;    
    var currentPage = Convert.ToInt32(ViewData["CurrentPage"] ?? 1);
    var userId = Model.Id;
    
    // Alert message handling
    var message = TempData["Message"];
    var isSuccess = TempData["isSuccess"] != null && (bool)TempData["isSuccess"];
    var alertClass = isSuccess ? "alert-success" : "alert-warning";
    var comeFrom = ViewBag.comeFrom;
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @* Alert Message Section *@
            <partial name="_AlertMessage" model='new { Message = message, AlertClass = alertClass }' />

            <h1 class="mb-4">@ViewBag.Title</h1>
            
            @* User Information Section *@
            <partial name="_UserCard" model="Model" />

            @* Action Buttons Section *@
            <partial name="_DetailActionButtons" model='new { 
                UserId = userId, 
                ComeFrom = comeFrom, 
                CurrentPage = currentPage 
            }' />
            
            <hr>

            @* Transactions Section *@
            <section id="transactions">
                <h3 class="mb-3">Transaction History</h3>
                @{
                    ViewData["ShowExportButton"] = true;
                    ViewBag.UserId = userId;
                }
                <partial name="_TransactionsTable" model="transactions" />
            </section>
            
            <hr>

            @* File Management Section *@
            <section id="fileManagement">
                <h3>File List</h3>
                <partial name="_FileUploadForm" model='new { UserId = userId, CurrentPage = currentPage }' />
                <partial name="_FileList" model="Model" />
            </section>
            
            <hr>

            @* Video Management Section *@
            <section id="videoManagement">
                <h3>Video</h3>
                <partial name="_VideoUploadForm" />
                <div id="videoList">
                    <partial name="_VideoList" model="Model" />
                </div>
            </section>
            
            <hr>

            @* Todo List Section *@
            <section id="todoList">
                <partial name="_TodoList" />
            </section>
        </div>
    </div>
</div>

@* Modals Section *@
<partial name="_CreateTransactionModal" />

@section Scripts {
    <script>
        window.videoConfig = {
            currentPage: @currentPage,
            userId: @userId,
        };
    </script>
    <script type="module" src="~/js/video-manager.js"></script>
    <script src="~/js/transaction-manager.js"></script>
}

WebApp/Views/User/Edit.cshtml
@model WebApp.Models.UserModel.User
@{
    ViewBag.Title = "Edit User";
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1>@ViewBag.Title</h1>
            <div class="row">
                <div class="col-md-6">
                    <form asp-controller="User" asp-action="Edit" method="post">
                        <div class="form-group mb-3">
                            <label asp-for="Username" class="control-label">Username</label>
                            <input asp-for="Username" class="form-control" value="@Model.Username"/>
                        </div>
            
                        <div class="form-group mb-3">
                            <label asp-for="Email" class="control-label">Email</label>
                            <input asp-for="Email" class="form-control" value="@Model.Email"/>
                        </div>

                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Confirm</button>
                            <a asp-controller="User" asp-action="Details" asp-route-id="@Model.Id" class="btn btn-secondary">Cancle</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebApp/Views/User/EditBudget.cshtml
@model IEnumerable<WebApp.Models.BudgetModel.Budget>;

@{
    var userId = ViewBag.userId;
    var currentPage = ViewBag.currentPage;
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1>@ViewBag.Title</h1>

            <div class="row">
                <div class="col-md-6">
                    <form asp-controller="User" asp-action="EditBudget" asp-route-id="@userId" asp-route-currentPage="@currentPage" method="post">
                        @foreach( var budget in Model){
                            <div class="form-group mb-3">
                                <label class="control-label">@budget.Category</label>
                                <input name="limits[@budget.Category]" value="@budget.Limit" class="form-control" type="number" step="0.01" />
                            </div>
                        }
                        <div class="form-group">
                            <button type="submit" class="btn btn-primary">Save</button>
                            <a asp-controller="User" asp-action="Details" asp-route-id="@userId" asp-route-currentPage="@currentPage" class="btn btn-secondary">Cancle</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

WebApp/Views/User/Index.cshtml
@model IEnumerable<WebApp.Models.UserModel.UserViewModel>
@{
    ViewBag.Title = "User Overview";
    var currentPage = Convert.ToInt32(ViewData["CurrentPage"] ?? 1);
    var message = TempData["Message"];
    var warning = TempData["Warning"];
}

@if (message != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @message
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
@if (warning != null)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @warning
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="mb-4">@ViewBag.Title</h1>
            <div class="mb-3 d-flex justify-content-between align-items-center">
                <a href="#" class="btn btn-primary" id="addUserBtn">
                    <i class="bi bi-plus-circle"></i> Add New User
                </a>
                <a asp-controller="User" asp-action="DeleteAllUser" class="btn btn-danger">Delete All User</a>
                <div>
                    <div class="btn-group">
                        <button type="button" class="btn btn-success dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                            Export
                        </button>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" asp-controller="ImportExport" asp-action="ExportAllUserToExcel">Excel</a></li>
                            <li><a class="dropdown-item" asp-controller="ImportExport" asp-action="ExportAllUserToPDF">PDF</a></li>
                        </ul>
                    </div>
                    <a asp-controller="ImportExport" asp-action="Import" asp-route-comeFrom="User" class="btn btn-warning">Import</a>
                </div>
            </div>
            <div class="list-group mb-3" id="tableContainer">
                @{await Html.RenderPartialAsync("_UsersTable", Model);}
            </div>
            <div id = "Pagination">
                @await Html.PartialAsync("_Pagination")
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="createUserModal" tabindex="-1" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add New User</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
      </div>
      <div class="modal-body" id="createUserModalBody">
        <!-- AJAX 會把 Partial 載進來 -->
      </div>
    </div>
  </div>
</div>

<script>
    window.userUrls = {
        createPartial: '@Url.Action("CreatePartial", "User")',
        createAjax: '@Url.Action("CreateAjax", "User")',
        usersTablePartial: '@Url.Action("UserTablePartial", "User", new {page = @currentPage})'
    };
    
</script>

<script src="~/js/user-create.js"></script>
<script type="module" src="~/js/pagination.js"></script>